apiVersion: v1
kind: Namespace
metadata:
  name: 100-avisos

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-demo
  namespace: 100-avisos
spec:
  replicas: 1
  selector:
    matchLabels:
      role: spring-demo
  template:
    metadata:
      labels:
        role: spring-demo
    spec:
      containers:
      - name: spring-demo
        image: iyustlop/spring-mongo-demo:0.0.1
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env-variables

---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
  namespace: 100-avisos
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    role: spring-demo