networks:
  monitoring:
    driver: bridge

volumes:
  mongodb: {}
  prometheus_data: {}
  grafana-data: {}

services:
  mongodb:
    image: mongo:latest
    container_name: manufacturer_mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${MONGODB_DATABASE}
    volumes:
      - ./mongodb:/data/db
    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')","--quiet"]
      interval: 5s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus:latest
    user: 1000:1000
    container_name: prometheus
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

  spring-mongo-demo:
    image: iyustlop/spring-mongo-demo:0.0.2
    build: .
    container_name: "springboot-mongodb"
    ports:
    - 8090:8080
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGODB_USERNAME=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    links:
      - prometheus