version: "3"
services:
  olivarmongo:
    image: mongo:latest
    container_name: "olivarmongo"
    ports:
    - 27017:27017
  spring-mongo-demo:
    image: iyustlop/spring-mongo-demo:1.0.0
    container_name: "springboot-mongodb"
    ports:
    - 8080:8080
    links:
      - olivarmongo