apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-demo-k8s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: spring-demo-k8s
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-demo-k8s
                port:
                  number: 8080