spring:
  data:
    mongodb:
      uri: mongodb://iyustlop:pass1234@mongodb:27017/manufacturer?authSource=admin
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080
